version: 0.2

phases:
  pre_build:
    commands:
      - echo Log into AWS ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - echo Logged in to AWS ECR successfully
  build:
    commands:
      - echo Building the Docker image...
      - ls -la
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Docker Image tagged with - $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
    finally: 
      - docker run --rm --entrypoint ls $IMAGE_REPO_NAME:$IMAGE_TAG /tmp
      - docker run --rm --entrypoint cat $IMAGE_REPO_NAME:$IMAGE_TAG /tmp/target/dependency-check-report.html > dependency-check-report.html
  post_build:
    commands:
      - echo Pushing docker image to ECR
      - ls -la
      - docker image ls
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Docker image pushed
      - printf '{"AWSEBDockerrunVersion":"1","Image":{"Name":"%s","Update":"true"},"Ports":[{"ContainerPort":"8080","HostPort":"8080"}],"EntryPoint":"java -jar /worldtime.jar"}' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG" > Dockerrun.aws.json
      - ls -la
      - cat Dockerrun.aws.json
artifacts:
  files:
    - Dockerrun.aws.json
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 
